--2020-09-07 06:48:55--  https://raw.githubusercontent.com/svenfuchs/rails-i18n/master/rails/locale/ja.yml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.108.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5117 (5.0K) [text/plain]
Saving to: ‘ja.yml’

     0K ....                                                  100% 53.0M=0s

2020-09-07 06:48:55 (53.0 MB/s) - ‘ja.yml’ saved [5117/5117]

